(* Exemplos de tipagem *)

let y = 2
let x = 1	(* alterar para 1 == 1 / 1 < 1 *)

if x then 
	for(y<-0 : 4.2 : 1){ 		(* alterar para 3 *)
		outputInt y
 	}
 	else
 		while (y == 2){          
 			outputFloat 5.2		(* colocar ; *)
 			y--	
 		}

(* Exibir a avaliação preguiçosa *)
if (true || (1/0 > 5)) 
	then (if (false || (1/0 < 4))   (* mudar para && *)
		then outputFloat 5.2 else outputString "Fim")

